"""add tax reports and taxpayer settings

Revision ID: 043d6a0ba49f
"""
from alembic import op
import sqlalchemy as sa

revision = '043d6a0ba49f'
down_revision = 'e4f91b0c62a7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('adapter_version', sa.String(), nullable=False),
    sa.Column('ledger_snapshot_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('output_dir', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tax_reports_country_year', 'tax_reports', ['country', 'tax_year'], unique=False)
    op.add_column('app_settings', sa.Column('default_country', sa.String(), nullable=True))
    op.add_column('app_settings', sa.Column('default_tax_year', sa.Integer(), nullable=True))
    op.add_column('app_settings', sa.Column('taxpayer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'taxpayer_name')
    op.drop_column('app_settings', 'default_tax_year')
    op.drop_column('app_settings', 'default_country')
    op.drop_index('ix_tax_reports_country_year', table_name='tax_reports')
    op.drop_table('tax_reports')
    # ### end Alembic commands ###
