"""add event addresses and fee recipient/manual flag

Revision ID: 35f87a631605
"""
from alembic import op
import sqlalchemy as sa

revision = '35f87a631605'
down_revision = '50defb87085d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('address_from', sa.String(), nullable=True))
    op.add_column('events', sa.Column('address_to', sa.String(), nullable=True))
    op.add_column('fees', sa.Column('fee_recipient', sa.String(), nullable=True))
    op.add_column('fees', sa.Column('manual', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fees', 'manual')
    op.drop_column('fees', 'fee_recipient')
    op.drop_column('events', 'address_to')
    op.drop_column('events', 'address_from')
    # ### end Alembic commands ###
