"""add structured event evidence fields

Revision ID: 50defb87085d
"""
from alembic import op
import sqlalchemy as sa

revision = '50defb87085d'
down_revision = 'bf59b9e1209a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('tx_hash', sa.String(), nullable=True))
    op.add_column('events', sa.Column('block_height', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('block_hash', sa.String(), nullable=True))
    op.add_column('events', sa.Column('log_index', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('contract_address', sa.String(), nullable=True))
    op.add_column('events', sa.Column('order_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('trade_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('deposit_id', sa.String(), nullable=True))
    op.add_column('events', sa.Column('withdrawal_id', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'withdrawal_id')
    op.drop_column('events', 'deposit_id')
    op.drop_column('events', 'trade_id')
    op.drop_column('events', 'order_id')
    op.drop_column('events', 'contract_address')
    op.drop_column('events', 'log_index')
    op.drop_column('events', 'block_hash')
    op.drop_column('events', 'block_height')
    op.drop_column('events', 'tx_hash')
    # ### end Alembic commands ###
