"""initial schema

Revision ID: 5567d8494b28
"""
from alembic import op
import sqlalchemy as sa

revision = '5567d8494b28'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('wallet_software', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('coingecko_id', sa.String(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'network', name='uq_asset_symbol_network')
    )
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_asset_id', sa.String(), nullable=False),
    sa.Column('quote_currency', sa.String(), nullable=False),
    sa.Column('observation_date', sa.String(), nullable=False),
    sa.Column('unit_price', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_asset_id', 'quote_currency', 'observation_date', name='uq_price_observation')
    )
    op.create_table('raw_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('connector_version', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_raw_event_source_external')
    )
    op.create_table('sync_state',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_imported', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('raw_event_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_subtype', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_timestamp', sa.String(), nullable=True),
    sa.Column('primary_asset_id', sa.Integer(), nullable=False),
    sa.Column('primary_amount', sa.String(), nullable=False),
    sa.Column('secondary_asset_id', sa.Integer(), nullable=True),
    sa.Column('secondary_amount', sa.String(), nullable=True),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('destination_label', sa.String(), nullable=True),
    sa.Column('counterparty', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('provenance', sa.String(), nullable=False),
    sa.Column('normalizer_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['primary_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ),
    sa.ForeignKeyConstraint(['secondary_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('fee_asset_id', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['fee_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('quote_currency', sa.String(), nullable=False),
    sa.Column('unit_price', sa.String(), nullable=False),
    sa.Column('total_value', sa.String(), nullable=False),
    sa.Column('requested_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_asset_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuations')
    op.drop_table('overrides')
    op.drop_table('issues')
    op.drop_table('fees')
    op.drop_table('events')
    op.drop_table('sync_state')
    op.drop_table('raw_events')
    op.drop_table('price_observations')
    op.drop_table('backup_records')
    op.drop_table('assets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
