"""add account connector fields

Revision ID: ac2f2dbf772b
"""
from alembic import op
import sqlalchemy as sa

revision = 'ac2f2dbf772b'
down_revision = '5567d8494b28'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('connector_type', sa.String(), nullable=False, server_default='manual'))
    op.add_column('accounts', sa.Column('chain_network', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('address', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('config_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'config_encrypted')
    op.drop_column('accounts', 'address')
    op.drop_column('accounts', 'chain_network')
    op.drop_column('accounts', 'connector_type')
    # ### end Alembic commands ###
