"""add report language

Revision ID: b4c6bd5c2475
"""
from alembic import op
import sqlalchemy as sa

revision = 'b4c6bd5c2475'
down_revision = '043d6a0ba49f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('default_language', sa.String(), nullable=True))
    op.add_column('tax_reports', sa.Column('language', sa.String(), nullable=False, server_default='en'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax_reports', 'language')
    op.drop_column('app_settings', 'default_language')
    # ### end Alembic commands ###
