"""add account paused flag

Revision ID: bf59b9e1209a
"""
from alembic import op
import sqlalchemy as sa

revision = 'bf59b9e1209a'
down_revision = '08543a528e36'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('paused', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'paused')
    # ### end Alembic commands ###
